name: CI / CD

on:
  pull_request:
  push:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  PYTHON_VERSION: "3.11"
  SERVICE_REPO_NAME: prolific-interview-service
  UI_REPO_NAME: prolific-interview-ui

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . pre-commit

      - name: Run pre-commit (all files)
        run: pre-commit run --all-files

      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -q
